--liquibase formatted sql

--changeset ayakovlev:010_insert_questions
INSERT INTO question (dcre, dmod, user_cre, user_mod, text, topic_id) VALUES
(now(), now(), 'admin', 'admin', 'Чем == отличается от equals()?', (SELECT id FROM topic WHERE name = 'Core Java')),
(now(), now(), 'admin', 'admin', 'Как работает hashCode() и зачем он нужен?', (SELECT id FROM topic WHERE name = 'Core Java')),
(now(), now(), 'admin', 'admin', 'Контракт equals() / hashCode()', (SELECT id FROM topic WHERE name = 'Core Java')),
(now(), now(), 'admin', 'admin', 'Что такое immutable-класс? Как сделать класс неизменяемым?', (SELECT id FROM topic WHERE name = 'Core Java')),
(now(), now(), 'admin', 'admin', 'Разница между String, StringBuilder, StringBuffer', (SELECT id FROM topic WHERE name = 'Core Java')),
(now(), now(), 'admin', 'admin', 'Что такое final (для переменных, методов, классов)?', (SELECT id FROM topic WHERE name = 'Core Java')),
(now(), now(), 'admin', 'admin', 'Autoboxing / unboxing — подводные камни', (SELECT id FROM topic WHERE name = 'Core Java')),
(now(), now(), 'admin', 'admin', 'Как работает clone()?', (SELECT id FROM topic WHERE name = 'Core Java')),
(now(), now(), 'admin', 'admin', 'Разница между Comparable и Comparator', (SELECT id FROM topic WHERE name = 'Core Java')),
(now(), now(), 'admin', 'admin', 'Что такое Optional и когда его стоит использовать?', (SELECT id FROM topic WHERE name = 'Core Java')),
(now(), now(), 'admin', 'admin', 'Что такое transient и volatile?', (SELECT id FROM topic WHERE name = 'Core Java')),

(now(), now(), 'admin', 'admin', 'Разница между ArrayList и LinkedList', (SELECT id FROM topic WHERE name = 'Collections Framework')),
(now(), now(), 'admin', 'admin', 'HashMap vs TreeMap vs LinkedHashMap', (SELECT id FROM topic WHERE name = 'Collections Framework')),
(now(), now(), 'admin', 'admin', 'Как работает HashMap внутри?', (SELECT id FROM topic WHERE name = 'Collections Framework')),
(now(), now(), 'admin', 'admin', 'Что происходит при коллизиях в HashMap?', (SELECT id FROM topic WHERE name = 'Collections Framework')),
(now(), now(), 'admin', 'admin', 'Почему HashMap не потокобезопасен?', (SELECT id FROM topic WHERE name = 'Collections Framework')),
(now(), now(), 'admin', 'admin', 'Чем Set отличается от List?', (SELECT id FROM topic WHERE name = 'Collections Framework')),
(now(), now(), 'admin', 'admin', 'В чем разница между Iterator и ListIterator?', (SELECT id FROM topic WHERE name = 'Collections Framework')),
(now(), now(), 'admin', 'admin', 'Fail-fast vs fail-safe итераторы', (SELECT id FROM topic WHERE name = 'Collections Framework')),
(now(), now(), 'admin', 'admin', 'Когда использовать CopyOnWriteArrayList?', (SELECT id FROM topic WHERE name = 'Collections Framework')),

(now(), now(), 'admin', 'admin', 'Что такое thread-safe?', (SELECT id FROM topic WHERE name = 'Многопоточность')),
(now(), now(), 'admin', 'admin', 'Способы создания потоков в Java', (SELECT id FROM topic WHERE name = 'Многопоточность')),
(now(), now(), 'admin', 'admin', 'synchronized vs Lock', (SELECT id FROM topic WHERE name = 'Многопоточность')),
(now(), now(), 'admin', 'admin', 'Что такое volatile и когда он нужен?', (SELECT id FROM topic WHERE name = 'Многопоточность')),
(now(), now(), 'admin', 'admin', 'Что такое deadlock и как его избежать?', (SELECT id FROM topic WHERE name = 'Многопоточность')),
(now(), now(), 'admin', 'admin', 'wait() / notify() / notifyAll()', (SELECT id FROM topic WHERE name = 'Многопоточность')),
(now(), now(), 'admin', 'admin', 'Чем Runnable отличается от Callable?', (SELECT id FROM topic WHERE name = 'Многопоточность')),
(now(), now(), 'admin', 'admin', 'Future и CompletableFuture', (SELECT id FROM topic WHERE name = 'Многопоточность')),
(now(), now(), 'admin', 'admin', 'Thread Pool — зачем нужен и какие бывают?', (SELECT id FROM topic WHERE name = 'Многопоточность')),
(now(), now(), 'admin', 'admin', 'Java Memory Model (на базовом уровне)', (SELECT id FROM topic WHERE name = 'Многопоточность')),

(now(), now(), 'admin', 'admin', 'Структура памяти JVM', (SELECT id FROM topic WHERE name = 'JVM и память')),
(now(), now(), 'admin', 'admin', 'Heap vs Stack', (SELECT id FROM topic WHERE name = 'JVM и память')),
(now(), now(), 'admin', 'admin', 'Что такое Garbage Collector?', (SELECT id FROM topic WHERE name = 'JVM и память')),
(now(), now(), 'admin', 'admin', 'Виды GC (Serial, Parallel, CMS, G1 — на уровне понимания)', (SELECT id FROM topic WHERE name = 'JVM и память')),
(now(), now(), 'admin', 'admin', 'Minor GC vs Major GC', (SELECT id FROM topic WHERE name = 'JVM и память')),
(now(), now(), 'admin', 'admin', 'Что такое Stop-the-World?', (SELECT id FROM topic WHERE name = 'JVM и память')),
(now(), now(), 'admin', 'admin', 'Что такое memory leak в Java?', (SELECT id FROM topic WHERE name = 'JVM и память')),

(now(), now(), 'admin', 'admin', 'Checked vs Unchecked exceptions', (SELECT id FROM topic WHERE name = 'Исключения')),
(now(), now(), 'admin', 'admin', 'try-catch-finally — как работает finally?', (SELECT id FROM topic WHERE name = 'Исключения')),
(now(), now(), 'admin', 'admin', 'Когда создавать собственное исключение?', (SELECT id FROM topic WHERE name = 'Исключения')),
(now(), now(), 'admin', 'admin', 'throw vs throws', (SELECT id FROM topic WHERE name = 'Исключения')),
(now(), now(), 'admin', 'admin', 'Что будет, если исключение выброшено в finally?', (SELECT id FROM topic WHERE name = 'Исключения')),

(now(), now(), 'admin', 'admin', 'Основные принципы ООП', (SELECT id FROM topic WHERE name = 'ООП и принципы')),
(now(), now(), 'admin', 'admin', 'SOLID — кратко каждый принцип', (SELECT id FROM topic WHERE name = 'ООП и принципы')),
(now(), now(), 'admin', 'admin', 'Композиция vs наследование', (SELECT id FROM topic WHERE name = 'ООП и принципы')),
(now(), now(), 'admin', 'admin', 'Переопределение vs перегрузка методов', (SELECT id FROM topic WHERE name = 'ООП и принципы')),
(now(), now(), 'admin', 'admin', 'Что такое polymorphism на практике?', (SELECT id FROM topic WHERE name = 'ООП и принципы')),

(now(), now(), 'admin', 'admin', 'Что такое Lambda?', (SELECT id FROM topic WHERE name = 'Java 8+')),
(now(), now(), 'admin', 'admin', 'Functional interfaces', (SELECT id FROM topic WHERE name = 'Java 8+')),
(now(), now(), 'admin', 'admin', 'Stream API: map, filter, flatMap, reduce', (SELECT id FROM topic WHERE name = 'Java 8+')),
(now(), now(), 'admin', 'admin', 'Lazy vs eager operations', (SELECT id FROM topic WHERE name = 'Java 8+')),
(now(), now(), 'admin', 'admin', 'Optional best practices', (SELECT id FROM topic WHERE name = 'Java 8+')),
(now(), now(), 'admin', 'admin', 'Разница между forEach и map', (SELECT id FROM topic WHERE name = 'Java 8+')),
(now(), now(), 'admin', 'admin', 'Parallel streams — когда опасны?', (SELECT id FROM topic WHERE name = 'Java 8+')),

(now(), now(), 'admin', 'admin', 'Что такое IoC и DI?', (SELECT id FROM topic WHERE name = 'Spring')),
(now(), now(), 'admin', 'admin', 'Жизненный цикл бина', (SELECT id FROM topic WHERE name = 'Spring')),
(now(), now(), 'admin', 'admin', '@Component, @Service, @Repository', (SELECT id FROM topic WHERE name = 'Spring')),
(now(), now(), 'admin', 'admin', '@Autowired vs constructor injection', (SELECT id FROM topic WHERE name = 'Spring')),
(now(), now(), 'admin', 'admin', 'Scope бинов', (SELECT id FROM topic WHERE name = 'Spring')),
(now(), now(), 'admin', 'admin', 'Что такое AOP и где применяется?', (SELECT id FROM topic WHERE name = 'Spring')),
(now(), now(), 'admin', 'admin', '@Transactional — как работает?', (SELECT id FROM topic WHERE name = 'Spring')),
(now(), now(), 'admin', 'admin', 'REST: разница между @Controller и @RestController', (SELECT id FROM topic WHERE name = 'Spring')),

(now(), now(), 'admin', 'admin', 'ACID', (SELECT id FROM topic WHERE name = 'Базы данных и SQL')),
(now(), now(), 'admin', 'admin', 'Индексы — зачем и как работают?', (SELECT id FROM topic WHERE name = 'Базы данных и SQL')),
(now(), now(), 'admin', 'admin', 'INNER JOIN vs LEFT JOIN', (SELECT id FROM topic WHERE name = 'Базы данных и SQL')),
(now(), now(), 'admin', 'admin', 'N+1 проблема', (SELECT id FROM topic WHERE name = 'Базы данных и SQL')),
(now(), now(), 'admin', 'admin', 'ORM vs JDBC', (SELECT id FROM topic WHERE name = 'Базы данных и SQL')),
(now(), now(), 'admin', 'admin', 'Hibernate: Lazy vs Eager loading', (SELECT id FROM topic WHERE name = 'Базы данных и SQL')),

(now(), now(), 'admin', 'admin', 'Как бы ты оптимизировал медленный запрос?', (SELECT id FROM topic WHERE name = 'Практические вопросы')),
(now(), now(), 'admin', 'admin', 'Как обрабатываешь ошибки в production?', (SELECT id FROM topic WHERE name = 'Практические вопросы')),
(now(), now(), 'admin', 'admin', 'Пример сложного бага, который ты решал?', (SELECT id FROM topic WHERE name = 'Практические вопросы')),
(now(), now(), 'admin', 'admin', 'Как пишешь unit-тесты?', (SELECT id FROM topic WHERE name = 'Практические вопросы')),
(now(), now(), 'admin', 'admin', 'Что выберешь: synchronized или ConcurrentHashMap и почему?', (SELECT id FROM topic WHERE name = 'Практические вопросы')),
(now(), now(), 'admin', 'admin', 'Какие у меня есть вопросы?', (SELECT id FROM topic WHERE name = 'Практические вопросы'));