spring.application.name=interview-prep

spring.datasource.url=jdbc:postgresql://localhost:5432/interview_prep
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

# To remove the error:
# Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ERROR: schema public not accessible
# Liquibase cannot access schema public in PostgreSQL.
spring.liquibase.default-schema=public
# This will give Liquibase permission to create its own service tables:
spring.jpa.properties.hibernate.default_schema=public

# Log SQL queries to the console
#spring.jpa.show-sql=true
# Format SQL for readability
spring.jpa.properties.hibernate.format_sql=true
# Enable parameter binding tracing
spring.jpa.properties.hibernate.type=trace
# Log the SQL statements themselves
logging.level.org.hibernate.SQL=DEBUG
# Log the actual parameter values bound to ?
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level ${PID} [inte] [%thread] %logger{20} - %msg%n
logging.charset.console=UTF-8

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

spring.profiles.active=local

