spring.application.name=interview-prep

spring.datasource.url=jdbc:postgresql://localhost:5432/interview_prep
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

# To remove the error:
# Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ERROR: schema public not accessible
# Liquibase cannot access schema public in PostgreSQL.
spring.liquibase.default-schema=public
# This will give Liquibase permission to create its own service tables:
spring.jpa.properties.hibernate.default_schema=public

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
logging.charset.console=UTF-8

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
