spring.application.name=job-pilot

spring.datasource.url=jdbc:postgresql://localhost:5432/jobpilot

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# This file is included in .gitignore in order not to share sensitive credentials.
spring.profiles.active=local

# To remove the error:
# Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: ERROR: schema public not accessible
# Liquibase cannot access schema public in PostgreSQL.
spring.liquibase.default-schema=public
# This will give Liquibase permission to create its own service tables:
spring.jpa.properties.hibernate.default_schema=public

server.port=8081
